version: '3'

services:
  reverse-proxy:
    image: traefik
    restart: always
    command: --docker --docker.domain=${LOCAL_DOMAIN} --logLevel=ERROR
    networks:
      - proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml:ro

networks:
  proxy:
    external: true
